### ISSUE TITLE
Cosine distance can be NaN

### ISSUE THREAD

**Issue by gabuzi** [vitrivr/cottontaildb#21] opened 2020-05-26 09:53 UTC
As of rev. eef57376, I have observed NaN values in the cosine distance calculation.

I suspect that it's caused by the norm2 method of the complex vector values that ultimately takes kotlin's Implementation of the square root of the real and imaginary part of the number, which can lead to NaNs if either of the imaginary or real part is negative (see excerpt from org.vitrivr.cottontail.model.values.Complex32Value below).

This does not lead to an error from the DB. Instead, results are returned for a KNN query without indication of a problem.

    override fun pow(x: Double): Complex64Value {
        val r = this.real.value.pow(x.toFloat()) + this.imaginary.value.pow(x.toFloat())
        val theta =  this.imaginary.value / this.real.value
        return Complex64Value(r * kotlin.math.cos(x*theta), r * kotlin.math.sin(x*theta))
    }

    override fun pow(x: Int): Complex64Value {
        val r = this.real.value.pow(x) + this.imaginary.value.pow(x)
        val theta =  this.imaginary.value / this.real.value
        return Complex64Value(r * kotlin.math.cos(x*theta), r * kotlin.math.sin(x*theta))
    }

    override fun sqrt(): Complex64Value = pow(1.0 / 2.0)

**Comment by ppanopticon** [comment] 2020-06-09 05:04
A agree with your suspicion as to what the cause of the problem might be. I have recently changed the basic arithmetic operations for **Complex32Value** and **Complex64Values**. Is this still an issue with the latest release?

I would argue that NaN, even though not desired as a result, is still a valid outcome of a calculation and therefore not something the execution engine should detect and handle. In this particular case, I guess the culprit was erroneous implementations of some basic operations.

**Comment by ppanopticon** [comment] 2020-07-08 12:01
This should have been fixed by now.

**Closed by ppanopticon** 2020-07-08 12:01 UTC
Labels: bug, good first issue
