### ISSUE TITLE
Distance column no longer present in knn query results

### ISSUE THREAD

**Issue by gabuzi** [vitrivr/cottontaildb#33] opened 2020-07-17 13:27 UTC
When submitting a query with a select * projection (the default if no projection is specified), the distance column is not present in the results. The column is removed by https://github.com/vitrivr/cottontaildb/blob/d97f827ddaeca22f75080c220e19df955a3c053d/src/main/kotlin/org/vitrivr/cottontail/execution/tasks/recordset/projection/RecordsetSelectProjectionTask.kt#L50

I remember that it was present at some point. Was this removed intentionally?

**Comment by ppanopticon** [comment] 2020-08-05 10:19
I'm afraid I cannot reproduce this issue. For example, this query returns all columns for me (i.e. the id, feature and distance column):

```kotlin
val query = CottontailGrpc.QueryMessage.newBuilder().setQuery(
                CottontailGrpc.Query.newBuilder()
                        .setFrom(CottontailGrpc.From.newBuilder().setEntity(CottontailGrpc.Entity.newBuilder().setName("features_averagecolor").setSchema(CottontailGrpc.Schema.newBuilder().setName("cineast")))) /* Entity to select data from. */
                        .setKnn(CottontailGrpc.Knn.newBuilder().setK(100).setAttribute("feature").setDistance(CottontailGrpc.Knn.Distance.L2).addQuery(CottontailGrpc.Vector.newBuilder().setFloatVector(vector))) /* kNN predicate on the column 'feature' with k = 10 and L2 distance. */
                        .setProjection(CottontailGrpc.Projection.newBuilder().putAttributes("*", "")) /* Selected attributes (id & calculated distance). */
        ).build()
        val results = this.dqlService.query(query)
        results.forEach {
            it.resultsList.forEach {
                println(it)
            }
        }
```

**Comment by gabuzi** [comment] 2020-08-10 08:19
I ran the query on the dev branch without explicitly setting a projection clause. As of fed257d0, there is no distance column in the returned results.
If I explicitly include a projection with `CottontailGrpc.Projection.newBuilder().putAttributes("*", "")`, the distance column is still not present in the query results.

**Comment by ppanopticon** [comment] 2020-08-10 12:47
Confirmed!

This is a an issue due to the new naming system on the dev-branch; requires some rework of the projection system which will come with the next iteration of the query planner.

**Comment by ppanopticon** [comment] 2020-09-29 11:41
This issue has been fixed on the dev branch.

**Closed by ppanopticon** 2020-09-29 11:41 UTC
