### ISSUE TITLE
EQUAL operator does not work for TEXT fields

### ISSUE THREAD

**Issue by silvanheller** [vitrivr/cottontaildb#16] opened 2019-12-09 10:03 UTC
LIKE gives correct results, = does not

**Comment by lucaro** [comment] 2019-12-09 12:39
Could you elaborate on what is not correct with the result? Is it empty, incomplete or does it contain invalid entries?

**Comment by silvanheller** [comment] 2019-12-09 12:55
No results. I assume the query is no propagated to the lucene index, therefore the query does not work (similar to if you had an unoptimized index)

**Comment by lucaro** [comment] 2019-12-09 13:08
Could you try if removing `|| it.operator == ComparisonOperator.EQUAL` from https://github.com/ppanopticon/cottontaildb/blob/master/src/main/kotlin/ch/unibas/dmi/dbis/cottontail/database/index/lucene/LuceneIndex.kt#L294 helps? Then at least we would know if the problem is with the lucene index...

**Comment by ppanopticon** [comment] 2020-06-09 07:53
This should have been fixed by now.

**Closed by ppanopticon** 2020-06-09 07:53 UTC
